### ISSUE TITLE
Renewal fails

### ISSUE THREAD

**Issue by Hermanverschooten** [dominicletz/certmagex#3]
I've been running one of my sites for a while and the customer contacted me today to tell me it was no longer reachable.
Upon trying the site I immediately noticed it was a certificate issue, I had had the e-mail from Let's encrypt to tell me the certificate was about to expire.

I checked the logs and found these entries repeatedly:

```elixir
Sep 14 16:10:06 kinecorman kine_corman[114]: 16:10:06.627 [error] GenServer CertMagex.Worker terminating
Sep 14 16:10:06 kinecorman kine_corman[114]: ** (KeyError) key "Replay-Nonce" at position 0 not found in: [{"Server", "nginx"}, {"Date", "Sat, 14 Sep 2024 16:10:06 GMT"}, {"Content-Type", "application/problem+json"}, {"Content-Length", "90"}, {"Connection", "keep-alive"}, {"Cache-Control", "private"}, {"Retry-After", "7"}]
Sep 14 16:10:06 kinecorman kine_corman[114]:     (elixir 1.17.2) lib/list.ex:381: List.keyfind!/3
Sep 14 16:10:06 kinecorman kine_corman[114]:     (zerossl 1.0.0) lib/acmev2.ex:259: Acmev2.get_nonce_from_resp/1
Sep 14 16:10:06 kinecorman kine_corman[114]:     (zerossl 1.0.0) lib/acmev2.ex:513: Acmev2.post_chall/2
Sep 14 16:10:06 kinecorman kine_corman[114]:     (zerossl 1.0.0) lib/acmev2.ex:477: Acmev2.processing_state_retry/4
Sep 14 16:10:06 kinecorman kine_corman[114]:     (zerossl 1.0.0) lib/acmev2.ex:776: Acmev2.do_gen_cert/2
Sep 14 16:10:06 kinecorman kine_corman[114]:     (certmagex 1.0.4) lib/certmagex/worker.ex:25: CertMagex.Worker.handle_call/3
Sep 14 16:10:06 kinecorman kine_corman[114]:     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
Sep 14 16:10:06 kinecorman kine_corman[114]:     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
Sep 14 16:10:06 kinecorman kine_corman[114]: Last message (from #PID<0.3435.0>): {:gen_cert, "kinecorman.be"}
Sep 14 16:10:07 kinecorman kine_corman[114]: 16:10:06.994 [error] :gen_statem #PID<0.4119.0> terminating
Sep 14 16:10:07 kinecorman kine_corman[114]: ** (stop) exited in: GenServer.call(CertMagex.Worker, {:gen_cert, "kinecorman.be"}, :infinity)
Sep 14 16:10:07 kinecorman kine_corman[114]:     ** (EXIT) an exception was raised:
Sep 14 16:10:07 kinecorman kine_corman[114]:         ** (KeyError) key "Replay-Nonce" at position 0 not found in: [{"Server", "nginx"}, {"Date", "Sat, 14 Sep 2024 16:10:06 GMT"}, {"Content-Type", "application/problem+json"}, {"Content-Length", "90"}, {"Connection", "keep-alive"}, {"Cache-Control", "private"}, {"Retry-After", "7"}]
Sep 14 16:10:07 kinecorman kine_corman[114]:             (elixir 1.17.2) lib/list.ex:381: List.keyfind!/3
Sep 14 16:10:07 kinecorman kine_corman[114]:             (zerossl 1.0.0) lib/acmev2.ex:259: Acmev2.get_nonce_from_resp/1
Sep 14 16:10:07 kinecorman kine_corman[114]:             (zerossl 1.0.0) lib/acmev2.ex:513: Acmev2.post_chall/2
Sep 14 16:10:07 kinecorman kine_corman[114]:             (zerossl 1.0.0) lib/acmev2.ex:477: Acmev2.processing_state_retry/4
Sep 14 16:10:07 kinecorman kine_corman[114]:             (zerossl 1.0.0) lib/acmev2.ex:776: Acmev2.do_gen_cert/2
Sep 14 16:10:07 kinecorman kine_corman[114]:             (certmagex 1.0.4) lib/certmagex/worker.ex:25: CertMagex.Worker.handle_call/3
Sep 14 16:10:07 kinecorman kine_corman[114]:             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
Sep 14 16:10:07 kinecorman kine_corman[114]:             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
Sep 14 16:10:07 kinecorman kine_corman[114]:     (elixir 1.17.2) lib/gen_server.ex:1128: GenServer.call/3
Sep 14 16:10:07 kinecorman kine_corman[114]:     (certmagex 1.0.4) lib/certmagex.ex:96: CertMagex.gen_cert/1
Sep 14 16:10:07 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:1327: :ssl_gen_statem.update_ssl_options_from_sni/2
Sep 14 16:10:07 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:1294: :ssl_gen_statem.handle_sni_hostname/2
Sep 14 16:10:07 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:525: :ssl_gen_statem.handle_sni_extension/2
Sep 14 16:10:07 kinecorman kine_corman[114]:     (ssl 11.2.1) tls_dtls_server_connection.erl:335: :tls_dtls_server_connection.handle_sni_extension/2
Sep 14 16:10:07 kinecorman kine_corman[114]:     (ssl 11.2.1) tls_server_connection.erl:208: :tls_server_connection.hello/3
Sep 14 16:10:07 kinecorman kine_corman[114]:     (stdlib 6.0.1) gen_statem.erl:3113: :gen_statem.loop_state_callback/11
Sep 14 16:10:07 kinecorman kine_corman[114]: Process Label: {:tls, :server, "kinecorman.be", 443}
Sep 14 16:10:07 kinecorman kine_corman[114]: Queue: [internal: {:client_hello, {3, 1}, <<131, 119, 36, 171, 188, 50, 218, 111, 131, 45, 73, 92, 50, 171, 173, 35, 52, 210, 232, 73, 48, 39, 169, 82, 86, 219, 93, 194, 52, 179, 211, 250>>, "", :undefined, [<<192, 10>>, <<192, 9>>, <<192, 20>>, <<192, 19>>, <<0, 53>>, <<0, 47>>, <<192, 8>>, <<192, 18>>, <<0, 10>>, <<86, 0>>], %{srp: :undefined, elliptic_curves: {:elliptic_curves, [{1, 3, 101, 110}, {1, 2, 840, 10045, 3, 1, 7}, {1, 3, 132, 0, 34}, {1, 3, 132, 0, 35}]}, sni: {:sni, ~c"kinecorman.be"}, alpn: {:alpn, <<2, 104, 50, 8, 104, 116, 116, 112, 47, 49, 46, 49>>}, ec_point_formats: {:ec_point_formats, [0]}, next_protocol_negotiation: :undefined, renegotiation_info: {:renegotiation_info, <<0>>}}}]
Sep 14 16:10:07 kinecorman kine_corman[114]: Postponed: []
```

followed by:

```elixir
Sep 14 16:10:09 kinecorman kine_corman[114]: 16:10:09.140 [notice] Handler :default flushed 1377 log events
Sep 14 16:10:09 kinecorman kine_corman[114]: 16:10:09.151 [error] :gen_statem #PID<0.8317.0> terminating
Sep 14 16:10:09 kinecorman kine_corman[114]: ** (stop) exited in: GenServer.call(CertMagex.Storage, :get_handle, :infinity)
Sep 14 16:10:09 kinecorman kine_corman[114]:     ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
Sep 14 16:10:09 kinecorman kine_corman[114]:     (elixir 1.17.2) lib/gen_server.ex:1121: GenServer.call/3
Sep 14 16:10:09 kinecorman kine_corman[114]:     (dets_plus 2.4.2) lib/dets_plus.ex:449: DetsPlus.lookup/2
Sep 14 16:10:09 kinecorman kine_corman[114]:     (certmagex 1.0.4) lib/certmagex/storage.ex:37: CertMagex.Storage.lookup/1
Sep 14 16:10:09 kinecorman kine_corman[114]:     (certmagex 1.0.4) lib/certmagex.ex:79: CertMagex.cache_or_gen_cert/1
Sep 14 16:10:09 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:1327: :ssl_gen_statem.update_ssl_options_from_sni/2
Sep 14 16:10:09 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:1294: :ssl_gen_statem.handle_sni_hostname/2
Sep 14 16:10:09 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:525: :ssl_gen_statem.handle_sni_extension/2
Sep 14 16:10:09 kinecorman kine_corman[114]:     (ssl 11.2.1) tls_dtls_server_connection.erl:335: :tls_dtls_server_connection.handle_sni_extension/2
Sep 14 16:10:09 kinecorman kine_corman[114]: Process Label: {:tls, :server, "kinecorman.be", 443}
Sep 14 16:10:09 kinecorman kine_corman[114]: Queue: [internal: {:client_hello, {3, 1}, <<161, 29, 121, 133, 88, 34, 239, 206, 74, 24, 233, 205, 62, 73, 190, 182, 58, 232, 145, 119, 161, 230, 244, 1, 251, 48, 176, 42, 7, 104, 133, 68>>, "", :undefined, [<<192, 10>>, <<192, 9>>, <<192, 20>>, <<192, 19>>, <<0, 53>>, <<0, 47>>, <<192, 8>>, <<192, 18>>, <<0, 10>>, <<86, 0>>], %{srp: :undefined, elliptic_curves: {:elliptic_curves, [{1, 3, 101, 110}, {1, 2, 840, 10045, 3, 1, 7}, {1, 3, 132, 0, 34}, {1, 3, 132, 0, 35}]}, sni: {:sni, ~c"kinecorman.be"}, alpn: {:alpn, <<2, 104, 50, 8, 104, 116, 116, 112, 47, 49, 46, 49>>}, ec_point_formats: {:ec_point_formats, [0]}, next_protocol_negotiation: :undefined, renegotiation_info: {:renegotiation_info, <<0>>}}}]
Sep 14 16:10:09 kinecorman kine_corman[114]: Postponed: []
```
And the tail of the logs this morning was:
```elixir
Sep 16 07:22:52 kinecorman kine_corman[114]: 07:22:52.799 [error] GenServer #PID<0.20564.0> terminating
Sep 16 07:22:52 kinecorman kine_corman[114]: ** (stop) exited in: :gen_statem.call(#PID<0.20563.0>, {:start, :infinity}, :infinity)
Sep 16 07:22:52 kinecorman kine_corman[114]:     ** (EXIT) exited in: GenServer.call(CertMagex.Worker, {:gen_cert, "kinecorman.be"}, :infinity)
Sep 16 07:22:52 kinecorman kine_corman[114]:         ** (EXIT) an exception was raised:
Sep 16 07:22:52 kinecorman kine_corman[114]:             ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.3445.0>}}
Sep 16 07:22:52 kinecorman kine_corman[114]:                 (zerossl 1.0.0) lib/acmev2.ex:543: Acmev2.serve/1
Sep 16 07:22:52 kinecorman kine_corman[114]:                 (zerossl 1.0.0) lib/acmev2.ex:768: Acmev2.do_gen_cert/2
Sep 16 07:22:52 kinecorman kine_corman[114]:                 (certmagex 1.0.4) lib/certmagex/worker.ex:25: CertMagex.Worker.handle_call/3
Sep 16 07:22:52 kinecorman kine_corman[114]:                 (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
Sep 16 07:22:52 kinecorman kine_corman[114]:                 (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
Sep 16 07:22:52 kinecorman kine_corman[114]:                 (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Sep 16 07:22:52 kinecorman kine_corman[114]:     (stdlib 6.0.1) gen.erl:247: :gen.do_call/4
Sep 16 07:22:52 kinecorman kine_corman[114]:     (stdlib 6.0.1) gen_statem.erl:2633: :gen_statem.call/3
Sep 16 07:22:52 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:1267: :ssl_gen_statem.call/2
Sep 16 07:22:52 kinecorman kine_corman[114]:     (ssl 11.2.1) ssl_gen_statem.erl:315: :ssl_gen_statem.handshake/2
Sep 16 07:22:52 kinecorman kine_corman[114]:     (thousand_island 1.3.5) lib/thousand_island/transports/ssl.ex:94: ThousandIsland.Transports.SSL.handshake/1
Sep 16 07:22:52 kinecorman kine_corman[114]:     (thousand_island 1.3.5) lib/thousand_island/socket.ex:43: ThousandIsland.Socket.handshake/1
Sep 16 07:22:52 kinecorman kine_corman[114]:     (bandit 1.5.7) /home/runner/work/kinecorman/kinecorman/deps/thousand_island/lib/thousand_island/handler.ex:364: Bandit.DelegatingHandler.handle_info/2
Sep 16 07:22:52 kinecorman kine_corman[114]:     (stdlib 6.0.1) gen_server.erl:2173: :gen_server.try_handle_info/3
Sep 16 07:22:52 kinecorman kine_corman[114]: Last message: {:thousand_island_ready, {:sslsocket, {:gen_tcp, #Port<0.2965>, :tls_connection, [option_tracker: #PID<0.2428.0>, session_tickets_tracker: :disabled, session_id_tracker: #PID<0.2429.0>]}, [#PID<0.20563.0>, #PID<0.20562.0>]}, %ThousandIsland.ServerConfig{port: 443, transport_module: ThousandIsland.Transports.SSL, transport_options: [{:versions, [:"tlsv1.2"]}, {:ciphers, [~c"ECDHE-RSA-AES256-GCM-SHA384", ~c"ECDHE-ECDSA-AES256-GCM-SHA384", ~c"ECDHE-RSA-AES128-GCM-SHA256", ~c"ECDHE-ECDSA-AES128-GCM-SHA256", ~c"DHE-RSA-AES256-GCM-SHA384", ~c"DHE-RSA-AES128-GCM-SHA256"]}, {:eccs, [:secp256r1, :secp384r1, :secp521r1]}, {:honor_cipher_order, true}, :inet6, {:secure_renegotiate, true}, {:reuse_sessions, true}, {:log_level, :warning}, {:sni_fun, &CertMagex.sni_fun/1}, {:ip, {0, 0, 0, 0, 0, 0, 0, 0}}, {:alpn_preferred_protocols, ["h2", "http/1.1"]}], handler_module: Bandit.DelegatingHandler, handler_options: %{opts: %{http: [], websocket: [], http_2: [], http_1: []}, plug: {KineCormanWeb.Endpoint, []}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true}, genserver_options: [], supervisor_options: [], num_acceptors: 100, num_connections: 16384, max_connections_retry_count: 5, max_connections_retry_wait: 1000, read_timeout: 60000, shutdown_timeout: 15000, silent_terminate_on_error: false}, %ThousandIsland.Telemetry{span_name: :acceptor, telemetry_span_context: #Reference<0.1510299976.52428801.182749>, start_time: -576460747272985869, start_metadata: %{telemetry_span_context: #Reference<0.1510299976.52428801.182749>, parent_telemetry_span_context: #Reference<0.1510299976.52428801.182064>}}, -576185618675144461}
```

**Comment by Hermanverschooten** [comment]
I tried stopping starting the site, but then it just gave me 2 lines of 404 for the `.well-known/...` and no longer responded.
So I went back to `site_encrypt`.  But I wanted to let you know about the issue.

**Comment by Hermanverschooten** [comment]
```elixir
Sep 16 07:23:25 kinecorman systemd[1]: Started kine_corman.
Sep 16 07:23:28 kinecorman kine_corman[17397]: 07:23:28.619 [info] Running KineCormanWeb.Endpoint with Bandit 1.5.7 at :::80 (http)
Sep 16 07:23:28 kinecorman kine_corman[17397]: 07:23:28.632 [info] Running KineCormanWeb.Endpoint with Bandit 1.5.7 at :::443 (https)
Sep 16 07:23:28 kinecorman kine_corman[17397]: 07:23:28.639 [info] Access KineCormanWeb.Endpoint at https://kinecorman.be
Sep 16 07:23:35 kinecorman kine_corman[17397]: 07:23:35.221 request_id=F_WomtsqyMeoUoIAABfB [info] GET /.well-known/acme-challenge/lO3wBPGPdOI5jXbno9bKEjd1kEaWLDWpoO4YZJvVdaM
Sep 16 07:23:35 kinecorman kine_corman[17397]: 07:23:35.222 request_id=F_WomtsqyMeoUoIAABfB [info] Sent 404 in 243µs
Sep 16 07:23:35 kinecorman kine_corman[17397]: 07:23:35.451 request_id=F_WomujaKx2DYrgAABgB [info] GET /.well-known/acme-challenge/lO3wBPGPdOI5jXbno9bKEjd1kEaWLDWpoO4YZJvVdaM
Sep 16 07:23:35 kinecorman kine_corman[17397]: 07:23:35.451 request_id=F_WomujaKx2DYrgAABgB [info] Sent 404 in 148µs
```

These was what was logged after restarting.

**Comment by dominicletz** [comment]
Hey thanks for letting me know @Hermanverschooten 

Thee things I see here addressed:
- Created a PR to zerossl for the `:already_started` issue https://github.com/riccardomanfrin/zerossl/pull/7
- Added Storage to the Supervision tree in case there is an issue: https://github.com/dominicletz/certmagex/commit/73c6ddeefbeacca85c4c9ebbada3546370d602af
- Added a debounce to avoid the `Reply-After` responses: https://github.com/dominicletz/certmagex/commit/b5c0bca46f97dc5260b56845f1851a816b2cb481

This is released with certmagex v1.0.5

That said the first fix depends on zerossl releasing a new hex package. I've pinged the maintainer on that: https://github.com/riccardomanfrin/zerossl/issues/8

**Comment by Hermanverschooten** [comment]
I was already using the main branch, as the fix for IPv6 I introduced in March is not yet released.

**Comment by dominicletz** [comment]
That makes sense, I saw your patch and thought you must be using master already. Anyway all of these are good updates from today. If zerossl doesn't update soon I might copy the acme file into certmagex and remove the dependency.

**Comment by dominicletz** [comment]
zerossl updated hex now. I'm closing this.
